# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x07service\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\x0cTextResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1c\n\x0cJsonResponse\x12\x0c\n\x04json\x18\x01 \x01(\t2\xc0\x01\n\tMyService\x12\x39\n\nProcessLog\x12\x14.service.TextRequest\x1a\x15.service.JsonResponse\x12\x39\n\nShortenUrl\x12\x14.service.TextRequest\x1a\x15.service.TextResponse\x12=\n\x0e\x44\x65tectLanguage\x12\x14.service.TextRequest\x1a\x15.service.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=26
  _globals['_TEXTREQUEST']._serialized_end=53
  _globals['_TEXTRESPONSE']._serialized_start=55
  _globals['_TEXTRESPONSE']._serialized_end=85
  _globals['_JSONRESPONSE']._serialized_start=87
  _globals['_JSONRESPONSE']._serialized_end=115
  _globals['_MYSERVICE']._serialized_start=118
  _globals['_MYSERVICE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
